name: Build Finanzblick

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Docker Version
        run: docker --version

      - name: Docker Image bauen
        run: |
          docker build \
            -t finanzblick:latest \
            .
