name: Build and Push Finanzblick

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Docker Version
        run: docker --version

      - name: Docker Image bauen
        run: |
          docker build \
            -t gitea.alxserver.de/alexander/finanzblick:latest \
            .

      - name: Bei Gitea Container Registry anmelden
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | \
          docker login gitea.alxserver.de \
            --username "${{ secrets.REGISTRY_USER }}" \
            --password-stdin

      - name: Image zu Gitea pushen
        run: |
          docker push \
            gitea.alxserver.de/alexander/finanzblick:latest
